### PR TITLE
removed unwanted whitespaces

### PR DESCRIPTION
**Pull request by remipou**

### CODE REVIEW

**Comment by davidpaulsson** [comment]
Thanks!

**Comment by remipou** [comment]
tack själv!
är detta också en "horunge" eller är det ok?

before:

​after:

/Rémi PUIG
remi@fria.nu
​

2015-02-11 12:53 GMT+01:00 David Paulsson <notifications@github.com>:

**Comment by davidpaulsson** [comment]
I can't see any images. Either that or I simply don't understand what you mean :)

**Comment by remipou** [comment]
trying again :)
just wondering if this's ok or if "längst" in the middle is an orphan as well?

before:
skarmavbild 2015-02-11 kl 12 58 53
after:
skarmavbild 2015-02-11 kl 12 58 27

**Comment by davidpaulsson** [comment]
Hm, I guess this is a hard problem to overcome with these very long Swedish words we sometimes can encounter. Sorry, I'm not sure how to handle this.

**Comment by davidpaulsson** [comment]
You would get the same problem here

screen shot 2015-02-11 at 13 18 22

I guess i'd recommend a case by case usage. Hard with a CMS though. Tough.

**Pull request merged**
